### ISSUE TITLE
webpack 4 support

### ISSUE THREAD

**Issue by entr** [aharris/webpack-inline-svg-plugin#2]
Getting an error with webpack 4.12

```
.../node_modules/webpack-inline-svg-plugin/index.js:38
        chunk.modules.forEach(function (module){
                      ^

TypeError: Cannot read property 'forEach' of undefined
    at .../node_modules/webpack-inline-svg-plugin/index.js:38:23
    at Array.forEach (<anonymous>)
    at .../node_modules/webpack-inline-svg-plugin/index.js:37:14
    at SyncBailHook.eval [as call] (eval at create (.../node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook [as _call] (.../node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (.../node_modules/webpack/lib/Compilation.js:1196:30)
    at hooks.make.callAsync.err (.../node_modules/webpack/lib/Compiler.js:547:17)
    at _err0 (eval at create (.../node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (.../node_modules/webpack/lib/Compilation.js:1054:12)
    at processModuleDependencies.err (.../node_modules/webpack/lib/Compilation.js:980:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by aharris** [comment]
This was originally built with webpack@2.6.1.

Webpack 4 has changed a significant amount of things that affect this project. 

Example. They removed `chunk.modules` as well as the way I was previously tapping into the source of these chunks to replace the img tags. 

I am going to look further into updating this to work with the latest webpack.

Stay tuned.

Pull Requests always welcome :)
